# Generated by Django 4.0.2 on 2022-02-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_remove_voter_otp_remove_voter_otp_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(default='avatar.png', upload_to='candidates'),
        ),
    ]
