# Generated by Django 4.0.2 on 2022-02-12 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_alter_candidate_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='verified',
        ),
    ]
