# Generated by Django 4.0.2 on 2022-02-14 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_remove_voter_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='max_vote',
        ),
    ]
