# Generated by Django 4.0.2 on 2022-02-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_remove_position_max_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='no_vote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='votes',
            name='yes_vote',
            field=models.BooleanField(default=False),
        ),
    ]
