# Generated by Django 4.0.2 on 2022-02-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_votes_no_vote_votes_yes_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='countDown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time_counter', models.DateTimeField()),
                ('end_time_counter', models.DateTimeField()),
                ('view_flag', models.BooleanField(default=False)),
            ],
        ),
    ]
