# Generated by Django 4.0.2 on 2022-02-16 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_countdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countdown',
            name='start_time_counter',
        ),
    ]
