# Generated by Django 4.0.2 on 2022-02-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_countdown_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdown',
            name='view_flag',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='true', max_length=10),
        ),
    ]
